batch:
  size:
    max: 100000
datasource:
  tinyid:
    names: primary,secondary
    primary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ny_cloud_vue?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
      username: henry
      password: faith
      maxActive: 10
      testOnBorrow: false
    secondary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/henrydb?allowMultiQueries=true&amp;useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull&amp;autoReconnect=true
      username: henry
      password: faith
      maxActive: 10
      testOnBorrow: false
    type: com.zaxxer.hikari.HikariDataSource
