spring:
  rabbitmq:
    first:
      host: localhost
      port: 5672
      username: henry
      password: faith
      concurrency: 2
      prefetch: 1
    second:
      host: localhost
      port: 5672
      username: henry
      password: faith
      concurrency: 2
      prefetch: 1